# background    = "#fdfdfd",
# foreground    = "#000000",
# cursorcolor   = "#000000", or maybe #8CB4FF, or #85B3F2
# black         = "#242424",
# light_black   = "#666666",
# red           = "#c20a0a",
# light_red     = "#e06c6c",
# green         = "#38c20a",
# light_green   = "#89e06c",
# yellow        = "#da730b",
# light_yellow  = "#e9a663",
# blue          = "#0a66c2",
# light_blue    = "#63a6e9",
# magenta       = "#733fa6",
# light_magenta = "#b78fef",
# cyan          = "#0a94c2",
# light_cyan    = "#63c7e9",
# white         = "#cdcdcd",
# light_white   = "#eaeaea",


[colors.primary]
background = "#fdfdfd"
foreground = "#000000"
dim_foreground = "#242424"
bright_foreground = "#242424"

[colors.cursor]
text = "CellBackground"
cursor = "CellForeground"

[colors.vi_mode_cursor]
text = "#eaeaea"
cursor = "#7287FD"

[colors.search.matches]
foreground = "#000000"
background = "#fdfdfd"

[colors.search.focused_match]
foreground = "#eaeaea"
background = "#40A02B"

[colors.footer_bar]
foreground = "#eaeaea"
background = "#666666"

[colors.hints.start]
foreground = "#eaeaea"
background = "#DF8E1D"

[colors.hints.end]
foreground = "#eaeaea"
background = "#666666"

[colors.selection]
text = "#eaeaea"
background = "#da730b"

[colors.normal]
black   = "#242424"
red     = "#c20a0a"
green   = "#38c20a"
yellow  = "#da730b"
blue    = "#0a66c2"
magenta = "#733fa6"
cyan    = "#0a94c2"
white   = "#cdcdcd"

[colors.bright]
black   = "#666666"
red     = "#e06c6c"
green   = "#89e06c"
yellow  = "#e9a663"
blue    = "#63a6e9"
magenta = "#b78fef"
cyan    = "#63c7e9"
white   = "#eaeaea"

[colors.dim]
black   = "#242424"
red     = "#c20a0a"
green   = "#38c20a"
yellow  = "#da730b"
blue    = "#0a66c2"
magenta = "#733fa6"
cyan    = "#0a94c2"
white   = "#cdcdcd"

[[colors.indexed_colors]]
index = 16
color = "#da730b"

[[colors.indexed_colors]]
index = 17
color = "#e9a663"
